
[build]
  command = "npm run build"
  publish = ".next"
  
[template]
  incoming-hooks = ["Sanity"]

[template.environment]
  SANITY_TOKEN = "this is your Sanity token"
  SITE_LOGO = "https://www.netlify.com/logo-placeholder.svg"
